#!/bin/bash
JMX_HOST=127.0.0.1
JMX_PORT=8001
HTTP_PORT=8081
export JMX_AUTH="-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
export JMX="-Djava.rmi.server.hostname=$JMX_HOST -Dcom.sun.management.jmxremote.port=$JMX_PORT"
export QUARKUS_PORT="-Dquarkus.http.port=$HTTP_PORT"
$JAVA_HOME/bin/java $JMX $JMX_AUTH $QUARKUS_PORT -jar target/things-service-1.0.0-runner.jar
